name: topon_ad_plugin
description: A Flutter plugin for integrating TopOn Ads using Method Channels. Supports interstitial, rewarded, banner, native, and splash ads.
version: 0.0.8
homepage: https://github.com/jaiswal4sudeep/ToponAdPlugin
repository: https://github.com/jaiswal4sudeep/ToponAdPlugin
issue_tracker: https://github.com/jaiswal4sudeep/ToponAdPlugin/issues
documentation: https://github.com/jaiswal4sudeep/ToponAdPlugin#readme
topics:
  - ads
  - topon
  - interstitial
  - rewarded
  - monetization

environment:
  sdk: ^3.7.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.sudeep.topon_ad_plugin
        pluginClass: ToponAdPlugin