group = "com.sudeep.topon_ad_plugin"
version = "1.0"

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jfrog.anythinktech.com/artifactory/overseas_sdk" }
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.12.1")
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()

        // ✅ TopOn SDK
        maven { url "https://jfrog.anythinktech.com/artifactory/overseas_sdk" }

        // ✅ Mintegral
        maven { url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea" }
    }
}

apply plugin: "com.android.library"

android {
    namespace = "com.sudeep.topon_ad_plugin"
    compileSdk = 36

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdk = 24
    }

    testOptions {
        unitTests.all {
            testLogging {
                events "passed", "skipped", "failed", "standardOut", "standardError"
                outputs.upToDateWhen { false }
                showStandardStreams = true
            }
        }
    }
}

dependencies {
    // ✅ TU (Necessary)
    api "com.thinkup.sdk:core-tpn:6.6.30"
    
    // ✅ Androidx (Necessary)
    api "androidx.appcompat:appcompat:1.6.1"
    api "androidx.browser:browser:1.4.0"

    // ✅ Vungle
    api "com.thinkup.sdk:adapter-tpn-vungle:7.7.3.1.1"
    api "com.vungle:vungle-ads:7.7.3"
    api "com.google.android.gms:play-services-basement:18.1.0"
    api "com.google.android.gms:play-services-ads-identifier:18.0.1"

    // ✅ UnityAds
    api "com.thinkup.sdk:adapter-tpn-unityads:4.18.0.1.0"
    api "com.unity3d.ads:unity-ads:4.18.0"

    // ✅ Facebook
    api "com.thinkup.sdk:adapter-tpn-facebook:6.21.0.1.1"
    api "com.facebook.android:audience-network-sdk:6.21.0"
    api "androidx.annotation:annotation:1.0.0"

    // ✅ Admob
    api "com.thinkup.sdk:adapter-tpn-admob:25.4.0.1.1"
    api "com.google.android.gms:play-services-ads:25.4.0"

    // ✅ Inmobi
    api "com.thinkup.sdk:adapter-tpn-inmobi:11.1.1.1.2"
    api "com.inmobi.monetization:inmobi-ads-kotlin:11.1.1"

    // ✅ Mintegral
    api "com.thinkup.sdk:adapter-tpn-mintegral:17.1.61.1.1"
    api "com.mbridge.msdk.oversea:mbridge_android_sdk:17.1.61"
    api "androidx.recyclerview:recyclerview:1.1.0"
}
